export const FETCH_POKE_REQUEST = 'FETCH_POKE_REQUEST';
export const FETCH_POKE_SUCCESS = 'FETCH_POKE_SUCCESS';
export const FETCH_POKE_FAILURE = 'FETCH_POKE_FAILURE';
export const MAXIMUM_SAVINGS = 'MAXIMUM_SAVINGS';